version: '3.7'

services:
    frontend:
        build:
            context: .
            dockerfile: Dockerfile.nginx
        ports:
            - "5000:5000"
        networks:
            - frontend
            - backend
    backend:
        build:
            context: .
            dockerfile: Dockerfile
        networks:
            - backend

networks:
    frontend:
    backend:
